                  List of relations
 Schema |         Name          | Type  |   Owner    
--------+-----------------------+-------+------------
 public | active_admin_comments | table | desarrollo
 public | additional_cards      | table | desarrollo
 public | admin_users           | table | desarrollo
 public | annex_images          | table | desarrollo
 public | app_versions          | table | desarrollo
 public | ar_internal_metadata  | table | desarrollo
 public | audits                | table | desarrollo
 public | bills                 | table | desarrollo
 public | bills_insurances      | table | desarrollo
 public | body_areas            | table | desarrollo
 public | client_users          | table | desarrollo
 public | clients               | table | desarrollo
 public | consultation_controls | table | desarrollo
 public | consultations         | table | desarrollo
 public | contacts              | table | desarrollo
 public | contracts             | table | desarrollo
 public | departments           | table | desarrollo
 public | designed_responses    | table | desarrollo
 public | devices               | table | desarrollo
 public | diseases              | table | desarrollo
 public | formulas              | table | desarrollo
 public | help_desks            | table | desarrollo
 public | history_tickets       | table | desarrollo
 public | images_injuries       | table | desarrollo
 public | injuries              | table | desarrollo
 public | insurances            | table | desarrollo
 public | ips_insurances        | table | desarrollo
 public | kits                  | table | desarrollo
 public | library_analyses      | table | desarrollo
 public | library_specialists   | table | desarrollo
 public | medical_consultations | table | desarrollo
 public | medical_controls      | table | desarrollo
 public | mipres_files          | table | desarrollo
 public | municipalities        | table | desarrollo
 public | nurse_consultations   | table | desarrollo
 public | nurse_controls        | table | desarrollo
 public | other_diagnostics     | table | desarrollo
 public | patient_informations  | table | desarrollo
 public | patients              | table | desarrollo
 public | payment_histories     | table | desarrollo
 public | prepay_card_clients   | table | desarrollo
 public | prepay_cards          | table | desarrollo
 public | request_exams         | table | desarrollo
 public | request_images        | table | desarrollo
 public | requests              | table | desarrollo
 public | schema_migrations     | table | desarrollo
 public | sessions              | table | desarrollo
 public | specialist_responses  | table | desarrollo
 public | subsidiaries          | table | desarrollo
 public | system_manuals        | table | desarrollo
 public | traceability_admins   | table | desarrollo
 public | traceability_clients  | table | desarrollo
 public | traceability_consults | table | desarrollo
 public | traceability_controls | table | desarrollo
 public | user_clients          | table | desarrollo
 public | user_tokens           | table | desarrollo
 public | users                 | table | desarrollo
(57 rows)

